// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEOLBRWcwecF5m5u6loSva5W4QKDE1kC0',
    appId: '1:585187583522:web:dae4bdee0f67439abacc7b',
    messagingSenderId: '585187583522',
    projectId: 'instagramclone-d205f',
    authDomain: 'instagramclone-d205f.firebaseapp.com',
    storageBucket: 'instagramclone-d205f.appspot.com',
    measurementId: 'G-FSZS9JQ94E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsRQDeFyOnKp1F7fDAVUB--rzTkt-IDuo',
    appId: '1:585187583522:android:f244e842fa3f57e0bacc7b',
    messagingSenderId: '585187583522',
    projectId: 'instagramclone-d205f',
    storageBucket: 'instagramclone-d205f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5N6gWQExFIY8d0GaTcMJGscrB6KTeMac',
    appId: '1:585187583522:ios:439a45416a56af55bacc7b',
    messagingSenderId: '585187583522',
    projectId: 'instagramclone-d205f',
    storageBucket: 'instagramclone-d205f.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
